name: CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@master
      with:
        version: latest
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    # - run: echo $service_key > /tmp/service_key.json
    #   env:
    #     service_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    - run: yarn install
    - run: yarn test --runInBand --coverage --watchAll=false
      env:
        CI: true
        # GOOGLE_APPLICATION_CREDENTIALS: /tmp/service_key.json

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@master
      with:
        version: latest
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true
    - run: gcloud info
    # - run: |
    #     # Deploy cypher pubsub
    #     gcloud functions deploy cypherPubsub \
    #       --ingress-settings=all --runtime=nodejs12 \
    #       --allow-unauthenticated --timeout=300 \
    #       --service-account=$(gcloud config list account --format "value(core.account)") \
    #       --set-env-vars GCP_PROJECT=${{ secrets.GCP_PROJECT_ID }} \
    #       --set-env-vars URI_SECRET=projects/graphs-are-everywhere/secrets/NEO4J_URI/versions/latest \
    #       --set-env-vars USER_SECRET=projects/graphs-are-everywhere/secrets/NEO4J_USER/versions/latest \
    #       --set-env-vars PASSWORD_SECRET=projects/graphs-are-everywhere/secrets/NEO4J_PASSWORD/versions/latest \
    #       --trigger-topic cypher
    - run: |
        # Deploy custom cypher pubsub for image annotations
        # echo "GCP_PROJECT: blue-sytkbj >> /tmp/env.yaml
        # echo "URI_SECRET: projects/blue-sytkbj/secrets/NEO4J_URI/versions/latest" >> /tmp/env.yaml
        # echo "USER_SECRET: projects/blue-sytkbj/secrets/NEO4J_USER/versions/latest" >> /tmp/env.yaml
        # echo "PASSWORD_SECRET: projects/blue-sytkbj/secrets/NEO4J_PASSWORD/versions/latest" >> /tmp/env.yaml
        # echo 'CYPHER: "MERGE (i:Image {uri:event.uri}) MERGE (l:Label { mid: event.mid, description: event.description }) MERGE (i)-[:LABELED {score:event.score, confidence:event.confidence, topicality:event.topicality}]->(l)"' >> /tmp/env.yaml

        # cat /tmp/env.yaml
        ls -l
        pwd

        gcloud functions deploy imageAnnotationsToNeo4j \
          --entry-point=customCypherPubsub \
          --project=blue-sytkbj \
          --ingress-settings=all --runtime=nodejs14 \
          --allow-unauthenticated --timeout=300 \
          --service-account=hackathon-neo4j@blue-sytkbj.iam.gserviceaccount.com \
          --env-vars-file ./.env \
          --trigger-topic imageAnnotation
      